---
- name: Infrastructure managemnet
  hosts: localhost
  gather_facts: False
  connection: local
  vars_files:
  - group_vars/all/pass.yml
  no_log: True
  tasks:
  - name: Launch ec2 instance
    ec2:
        instance_type: t2.micro
        region: us-east-1
        image: ami-0ec41833a8034f411
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
